export const IMAGE_PLAYGROUND_STORAGE_KEY = "fluxio.image_playground.project.v1";

export const CANVAS_SIZE_PRESETS = [
  { id: "square", label: "Square", width: 1024, height: 1024 },
  { id: "portrait", label: "Portrait", width: 1024, height: 1536 },
  { id: "landscape", label: "Landscape", width: 1536, height: 1024 },
  { id: "wide", label: "Wide", width: 1792, height: 1024 },
];

export const IMAGE_TOOL_DEFINITIONS = [
  { id: "select", label: "Select", hint: "Move, resize, and reorder layers." },
  { id: "region", label: "Region", hint: "Mark an area for inpainting or continuation." },
  { id: "mask", label: "Mask", hint: "Prepare mask-guided edits." },
  { id: "compare", label: "Compare", hint: "Review previous generations." },
];

export const IMAGEGEN_LIBRARY_ARTIFACT = {
  id: "design-ref-imagegen-cyberpunk-20260513",
  title: "ImageGen cyberpunk gallery artifact",
  kind: "generated-image",
  artifactPath: ".agent_control/generated_image_artifacts/imagegen_cyberpunk_gallery_20260513T005434Z/imagegen_cyberpunk_gallery_20260513T005434Z.png",
  manifestPath: ".agent_control/generated_image_artifacts/imagegen_cyberpunk_gallery_20260513T005434Z/imagegen_cyberpunk_gallery_20260513T005434Z.manifest.json",
  requestId: "imagegen_cyberpunk_gallery_20260513T005434Z",
  artifactId: "imagegen_cyberpunk_gallery_20260513T005434Z",
  source: "codex_builtin_imagegen_skill",
  provider: "Codex ImageGen skill",
  artifactSha256: "1e91e1193363f9bfb7291cf66926b0d33fd39dc11b456dcb69a3963880c5386e",
  manifestSha256: "aed705ef42747d33df681c38993f8c75b5a16f99d00c8660bb6a0dbe8a0ce986",
  selected: true,
  rationale: "Real bitmap generated by the Codex ImageGen skill and served by the local/NAS artifact endpoint.",
};

export const DEFAULT_IMAGE_PROJECT = {
  id: "image-project-local",
  title: "Untitled image workspace",
  updatedAt: "",
  canvas: {
    width: 1024,
    height: 1024,
    background: "#111313",
    zoom: 0.62,
  },
  prompt: {
    mode: "generate",
    text: "A cinematic product workspace for autonomous creative agents, elegant dark glass interface, precise lighting, high-end editorial design",
    negative: "blurry, low quality, distorted typography",
    style: "editorial photoreal, subtle gold accents, cinematic lighting",
    strength: 0.72,
    preserveComposition: true,
  },
  provider: {
    id: "codex_subscription_gpt_image2",
    model: "gpt-image-2",
    quality: "high",
    size: "1024x1024",
  },
  chromaKey: {
    enabled: true,
    keyColor: "#00ff66",
    tolerance: 28,
    spillCleanup: 44,
    edgeFeather: 12,
    matteMode: "remove_background",
    replacementIntent: "transparent alpha matte with clean product edges",
    proofLabels: ["key color sampled", "spill cleanup planned", "edge feather planned"],
  },
  designReferences: [
    IMAGEGEN_LIBRARY_ARTIFACT,
    {
      id: "design-ref-a",
      title: "Prompt A",
      kind: "prompt-pack",
      prompt: "A premium AI image playground interface for a professional coding assistant app, dark neutral workspace, right-side generation queue with real thumbnails, provider status, request timeline, layer handoff, artifact path, compact metadata chips, annotation pins on images, clean mobile-collapsed cards, calm subtle progress animation, no marketing hero, dense but readable SaaS workbench, high-end product design, crisp typography, practical controls.",
      selected: true,
      rationale: "Primary operational dark workbench baseline.",
    },
    {
      id: "design-ref-b",
      title: "Prompt B",
      kind: "prompt-pack",
      prompt: "An AI image playground using its own generated design boards to improve itself: central canvas with generated visual references, left prompt/layer controls, right evidence queue, bottom timeline with queued -> provider accepted -> generating -> artifact written -> layer handoff -> verified, visible test receipts, professional annotations and issue pins, polished dark/light compatible operational UI.",
      selected: true,
      rationale: "Self-improving reference flow and explicit queue timeline stages.",
    },
    {
      id: "design-ref-codex-20260511T071327Z",
      title: "Codex generated workbench reference",
      kind: "generated-image",
      artifactPath: ".agent_control/design_references/codex_image_artifacts/codex_image_playground_live_review_reference_20260511T071327Z.png",
      manifestPath: ".agent_control/design_references/codex_image_artifacts/codex_image_playground_live_review_reference_20260511T071327Z.manifest.json",
      requestId: "codex_image_playground_live_review_reference_20260511T071327Z",
      artifactId: "codex_image_playground_live_review_reference_20260511T071327Z",
      source: "codex_builtin_image_gen",
      artifactSha256: "b975311c01c0cf80cf5d7af5f2d90506820e23f4e242d80a34224a592a50ae5c",
      manifestSha256: "7b6fca2704c5b4c5e8bfc102cce95070af06174ba085208fe435f1d0f62e5c96",
      selected: true,
      rationale: "Real Codex-generated design artifact consumed directly by Image Playground without NAS FAL_KEY dependency.",
    },
  ],
  annotationReadiness: {
    pins: [],
    rectangles: [],
    layers: [],
    comments: [],
  },
  skillsEvidence: [],
  focusedHistoryId: "",
  opsThreads: [],
  selectedLayerId: "layer-subject",
  activeTool: "select",
  selection: {
    x: 585,
    y: 300,
    width: 250,
    height: 230,
    feather: 18,
    visible: true,
  },
  layers: [
    {
      id: "layer-background",
      name: "Generated base",
      type: "shape",
      locked: true,
      visible: true,
      opacity: 1,
      blendMode: "normal",
      x: 0,
      y: 0,
      width: 1024,
      height: 1024,
      rotation: 0,
      fill: "radial-gradient(circle at 28% 18%, rgba(214,168,79,.42), transparent 22%), radial-gradient(circle at 72% 42%, rgba(94,138,170,.30), transparent 28%), linear-gradient(135deg, #101313, #1c2221 58%, #0b0e0e)",
      promptRole: "base image",
    },
    {
      id: "layer-subject",
      name: "Movable hero object",
      type: "shape",
      locked: false,
      visible: true,
      opacity: 0.96,
      blendMode: "screen",
      x: 354,
      y: 266,
      width: 292,
      height: 236,
      rotation: -4,
      fill: "linear-gradient(145deg, rgba(255,255,255,.72), rgba(214,168,79,.28) 52%, rgba(142,203,111,.12)), radial-gradient(circle at 35% 28%, rgba(255,255,255,.88), transparent 20%)",
      radius: 36,
      promptRole: "object to preserve after manual repositioning",
    },
    {
      id: "layer-shadow",
      name: "Contact shadow",
      type: "shape",
      locked: false,
      visible: true,
      opacity: 0.34,
      blendMode: "multiply",
      x: 330,
      y: 486,
      width: 350,
      height: 74,
      rotation: -4,
      fill: "radial-gradient(ellipse, rgba(0,0,0,.95), rgba(0,0,0,0) 70%)",
      radius: 999,
      promptRole: "shadow / grounding",
    },
  ],
  history: [
    {
      id: "hist-imagegen-cyberpunk-20260513",
      title: "ImageGen gallery artifact",
      prompt: "Cyberpunk rain-soaked city street at night with neon reflections, cinematic architectural depth.",
      provider: "Codex ImageGen skill",
      providerId: "codex-imagegen-skill",
      createdAt: "2026-05-13T00:54:34+02:00",
      status: "generated",
      requestId: "imagegen_cyberpunk_gallery_20260513T005434Z",
      providerStatus: "available",
      outputArtifactPath: IMAGEGEN_LIBRARY_ARTIFACT.artifactPath,
      previewSrc: IMAGEGEN_LIBRARY_ARTIFACT.artifactPath,
      manifestPath: IMAGEGEN_LIBRARY_ARTIFACT.manifestPath,
      manifestUrl: IMAGEGEN_LIBRARY_ARTIFACT.manifestPath,
      layerCount: 1,
      receipt: {
        promptHash: "1e91e1193363",
        providerName: "Codex ImageGen skill",
        fallback: "Real ImageGen artifact",
        testStatus: "Checked",
      },
    },
  ],
};

export function isRealImageSession(item) {
  if (!item || typeof item !== "object") return false;
  const provider = String(item.provider || item.providerId || "").toLowerCase();
  if (provider.includes("local composition") || provider === "local project") return false;
  const requestId = String(item.requestId || "").trim();
  const status = String(item.status || "").toLowerCase();
  const providerStatus = String(item.providerStatus || "").toLowerCase();
  const persistedArtifact = [
    item.outputArtifactPath,
    item.manifestPath,
    item.manifestUrl,
    item.artifactPath,
    item.previewSrc,
  ].some(value => {
    const source = String(value || "").trim();
    return source && !source.startsWith("data:");
  });
  if (status.includes("provider_blocked") || providerStatus === "blocked") {
    return Boolean(requestId) && (provider.includes("codex") || provider.includes("openai"));
  }
  return Boolean(requestId && persistedArtifact) && (
    status.includes("generated") ||
    status.includes("edited") ||
    providerStatus === "available"
  );
}

export function nowIso() {
  return new Date().toISOString();
}

export function makeId(prefix = "id") {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

export function keyboardScopeLabel(scope) {
  return scope === "queue" ? "Queue" : "History";
}

export function buildKeyboardTraversalAnnouncement({
  fromScope = "history",
  fromIndex = 0,
  fromCount = 0,
  toScope = "history",
  toIndex = 0,
  toCount = 0,
  reason = "focus",
} = {}) {
  const fromText = `${keyboardScopeLabel(fromScope)} ${Math.max(0, Number(fromIndex) || 0)}/${Math.max(0, Number(fromCount) || 0)}`;
  const toText = `${keyboardScopeLabel(toScope)} ${Math.max(0, Number(toIndex) || 0)}/${Math.max(0, Number(toCount) || 0)}`;
  if (reason === "group-jump" || reason === "edge-jump") {
    return `${fromText} -> ${toText}`;
  }
  return `${toText} focused`;
}

export function appendKeyboardJumpTrail(trail = [], transition = {}, options = {}) {
  const maxEntries = Math.max(1, Number(options.maxEntries) || 3);
  const nextEntry = {
    at: String(options.at || nowIso()),
    announcement: buildKeyboardTraversalAnnouncement(transition),
    fromScope: transition.fromScope || "history",
    toScope: transition.toScope || "history",
    reason: String(transition.reason || "focus"),
  };
  return [...(Array.isArray(trail) ? trail : []), nextEntry].slice(-maxEntries);
}

export function keyboardTraversalReasonLabel(reason = "focus") {
  const normalized = String(reason || "focus").toLowerCase();
  if (normalized === "group-jump") return "Scope jump";
  if (normalized === "edge-jump") return "Edge jump";
  if (normalized === "arrow") return "Arrow move";
  return "Focus";
}

export function formatKeyboardJumpTrailEntry(entry = {}) {
  const label = String(entry.announcement || "").trim() || "Traversal";
  const at = entry.at;
  if (!at) return label;
  try {
    const time = new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(at));
    return `${time} ${label}`;
  } catch {
    return `Recently ${label}`;
  }
}

export function formatKeyboardJumpTrailTooltip(entry = {}) {
  const label = String(entry.announcement || "").trim() || "Traversal";
  const reason = keyboardTraversalReasonLabel(entry.reason);
  const at = entry.at;
  if (!at) return `${reason} • ${label}`;
  try {
    const fullTime = new Intl.DateTimeFormat(undefined, {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    }).format(new Date(at));
    return `${fullTime} • ${reason} • ${label}`;
  } catch {
    return `${reason} • ${label}`;
  }
}

export function normalizeProject(project) {
  const base = structuredCloneSafe(DEFAULT_IMAGE_PROJECT);
  const next = { ...base, ...(project && typeof project === "object" ? project : {}) };
  next.canvas = { ...base.canvas, ...(next.canvas || {}) };
  next.prompt = { ...base.prompt, ...(next.prompt || {}) };
  next.provider = { ...base.provider, ...(next.provider || {}) };
  next.chromaKey = { ...base.chromaKey, ...(next.chromaKey || {}) };
  next.chromaKey.enabled = Boolean(next.chromaKey.enabled);
  next.chromaKey.keyColor = String(next.chromaKey.keyColor || base.chromaKey.keyColor);
  next.chromaKey.tolerance = Math.max(0, Math.min(100, Number(next.chromaKey.tolerance) || 0));
  next.chromaKey.spillCleanup = Math.max(0, Math.min(100, Number(next.chromaKey.spillCleanup) || 0));
  next.chromaKey.edgeFeather = Math.max(0, Math.min(64, Number(next.chromaKey.edgeFeather) || 0));
  next.designReferences = Array.isArray(next.designReferences) ? next.designReferences : base.designReferences;
  for (const reference of base.designReferences) {
    if (!next.designReferences.some(item => item?.id === reference.id || item?.artifactId === reference.artifactId)) {
      next.designReferences.unshift(reference);
    }
  }
  next.annotationReadiness = { ...base.annotationReadiness, ...(next.annotationReadiness || {}) };
  next.skillsEvidence = Array.isArray(next.skillsEvidence) ? next.skillsEvidence : base.skillsEvidence;
  next.focusedHistoryId = String(next.focusedHistoryId || "");
  next.opsThreads = Array.isArray(next.opsThreads) ? next.opsThreads : base.opsThreads;
  next.selection = { ...base.selection, ...(next.selection || {}) };
  next.layers = Array.isArray(next.layers) && next.layers.length ? next.layers : base.layers;
  next.history = (Array.isArray(next.history) ? next.history : base.history).filter(isRealImageSession);
  for (const item of base.history) {
    if (!next.history.some(entry => entry?.id === item.id || entry?.requestId === item.requestId)) {
      next.history.unshift(item);
    }
  }
  next.history = next.history.filter(isRealImageSession);
  next.updatedAt = next.updatedAt || nowIso();
  return next;
}

export function structuredCloneSafe(value) {
  if (typeof structuredClone === "function") {
    return structuredClone(value);
  }
  return JSON.parse(JSON.stringify(value));
}

export function loadImageProject() {
  if (typeof window === "undefined") {
    return normalizeProject();
  }
  try {
    const raw = window.localStorage.getItem(IMAGE_PLAYGROUND_STORAGE_KEY);
    return normalizeProject(raw ? JSON.parse(raw) : undefined);
  } catch {
    return normalizeProject();
  }
}

export function saveImageProject(project) {
  if (typeof window === "undefined") {
    return;
  }
  try {
    window.localStorage.setItem(IMAGE_PLAYGROUND_STORAGE_KEY, JSON.stringify(project));
  } catch {
    return;
  }
}

export function addHistoryEntry(project, entry) {
  const nextEntry = {
    id: makeId("hist"),
    createdAt: nowIso(),
    layerCount: project.layers.length,
    ...entry,
  };
  if (!isRealImageSession(nextEntry)) {
    return {
      ...project,
      updatedAt: nowIso(),
      history: (Array.isArray(project.history) ? project.history : []).filter(isRealImageSession),
    };
  }
  return {
    ...project,
    updatedAt: nowIso(),
    history: [nextEntry, ...(Array.isArray(project.history) ? project.history : [])]
      .filter(isRealImageSession)
      .slice(0, 40),
  };
}

export function projectToProviderPayload(project, operation = "edit", options = {}) {
  const normalized = normalizeProject(project);
  const layers = normalized.layers.map(layer => ({
    id: layer.id,
    name: layer.name,
    type: layer.type,
    visible: layer.visible,
    opacity: layer.opacity,
    blendMode: layer.blendMode,
    x: Math.round(layer.x),
    y: Math.round(layer.y),
    width: Math.round(layer.width),
    height: Math.round(layer.height),
    rotation: Number(layer.rotation || 0),
    promptRole: layer.promptRole || "",
    hasImage: Boolean(layer.src),
  }));
  const visibleLayers = layers.filter(layer => layer.visible !== false);
  return {
    operation,
    provider: normalized.provider,
    canvas: normalized.canvas,
    prompt: normalized.prompt,
    chromaKey: normalized.chromaKey,
    selection: normalized.selection,
    layers,
    compositionIntent: normalized.prompt.preserveComposition
      ? "Preserve the manual layer positions and selected region geometry as much as possible. Treat the canvas as the source composition for the next image operation."
      : "Use the canvas as loose visual context and allow broader reinterpretation.",
    inputs: {
      snapshotDataUrl: options.snapshotDataUrl || "",
      visibleLayerCount: visibleLayers.length,
      editRegion: {
        x: Math.round(normalized.selection.x || 0),
        y: Math.round(normalized.selection.y || 0),
        width: Math.round(normalized.selection.width || 0),
        height: Math.round(normalized.selection.height || 0),
        feather: Math.round(normalized.selection.feather || 0),
      },
    },
  };
}

export function createLayerFromSelection(project, options = {}) {
  const normalized = normalizeProject(project);
  const selection = normalized.selection || {};
  const layer = {
    id: options.id || makeId("layer-selection"),
    name: options.name || "Selected region",
    type: "shape",
    locked: false,
    visible: true,
    opacity: 0.78,
    blendMode: "screen",
    x: Math.round(selection.x || 0),
    y: Math.round(selection.y || 0),
    width: Math.max(1, Math.round(selection.width || 1)),
    height: Math.max(1, Math.round(selection.height || 1)),
    rotation: 0,
    fill: "linear-gradient(145deg, rgba(255,255,255,.58), rgba(214,168,79,.24))",
    radius: 20,
    mask: {
      feather: Math.max(0, Math.round(selection.feather || 0)),
    },
    promptRole: options.promptRole || "selected region",
  };
  return {
    ...normalized,
    selectedLayerId: layer.id,
    updatedAt: nowIso(),
    layers: [...normalized.layers, layer],
  };
}

export function updateLayerInProject(project, layerId, patch = {}) {
  const normalized = normalizeProject(project);
  return {
    ...normalized,
    updatedAt: nowIso(),
    layers: normalized.layers.map(layer => (layer.id === layerId ? { ...layer, ...patch } : layer)),
  };
}

export function removeLayerFromProject(project, layerId) {
  const normalized = normalizeProject(project);
  if (normalized.layers.length <= 1) {
    return normalized;
  }
  const nextLayers = normalized.layers.filter(layer => layer.id !== layerId);
  if (nextLayers.length === 0) {
    return normalized;
  }
  const selectedLayerId =
    normalized.selectedLayerId === layerId
      ? nextLayers[nextLayers.length - 1].id
      : normalized.selectedLayerId;
  return {
    ...normalized,
    updatedAt: nowIso(),
    layers: nextLayers,
    selectedLayerId,
  };
}

export function setFocusedHistoryItem(project, historyId) {
  const normalized = normalizeProject(project);
  const nextFocusedId = String(historyId || "");
  const target = normalized.history.find(item => item.id === nextFocusedId);
  const snapshot = target?.annotationSnapshot || {
    pins: [],
    rectangles: [],
    layers: [],
    comments: [],
  };
  return {
    ...normalized,
    focusedHistoryId: target ? target.id : "",
    annotationReadiness: {
      ...normalized.annotationReadiness,
      pins: Array.isArray(snapshot.pins) ? snapshot.pins : [],
      rectangles: Array.isArray(snapshot.rectangles) ? snapshot.rectangles : [],
      layers: Array.isArray(snapshot.layers) ? snapshot.layers : [],
      comments: Array.isArray(snapshot.comments) ? snapshot.comments : [],
    },
  };
}

export function updateFocusedHistoryAnnotations(project, annotationPatch = {}) {
  const normalized = normalizeProject(project);
  const focusedHistoryId = normalized.focusedHistoryId || normalized.history[0]?.id || "";
  const nextAnnotationReadiness = {
    ...normalized.annotationReadiness,
    ...annotationPatch,
  };
  const nextHistory = normalized.history.map(item => {
    if (item.id !== focusedHistoryId) {
      return item;
    }
    return {
      ...item,
      annotationSnapshot: {
        ...(item.annotationSnapshot || {}),
        pins: Array.isArray(nextAnnotationReadiness.pins) ? nextAnnotationReadiness.pins : [],
        rectangles: Array.isArray(nextAnnotationReadiness.rectangles) ? nextAnnotationReadiness.rectangles : [],
        layers: Array.isArray(nextAnnotationReadiness.layers) ? nextAnnotationReadiness.layers : [],
        comments: Array.isArray(nextAnnotationReadiness.comments) ? nextAnnotationReadiness.comments : [],
      },
    };
  });
  return {
    ...normalized,
    focusedHistoryId,
    updatedAt: nowIso(),
    annotationReadiness: nextAnnotationReadiness,
    history: nextHistory,
  };
}

export function createOpsThreadForFocusedHistory(project, options = {}) {
  const normalized = normalizeProject(project);
  const focusedHistoryId = normalized.focusedHistoryId || normalized.history[0]?.id || "";
  if (!focusedHistoryId) {
    return normalized;
  }
  const focused = normalized.history.find(item => item.id === focusedHistoryId);
  const requestId = focused?.requestId || "pending-request-id";
  const receiptHash = focused?.receipt?.promptHash || "unknown";
  const threadId = focused?.issueThread?.id || `${receiptHash}:${requestId}`;
  const existing = normalized.opsThreads.find(thread => thread.id === threadId);
  const stamp = nowIso();
  const threadRecord = existing || {
    id: threadId,
    historyId: focusedHistoryId,
    requestId,
    receiptHash,
    title: options.title || `Image Playground issue ${threadId}`,
    status: "open",
    createdAt: stamp,
    updatedAt: stamp,
    messages: [],
  };
  const opsThreads = existing
    ? normalized.opsThreads.map(thread => (thread.id === threadId ? { ...thread, updatedAt: stamp } : thread))
    : [threadRecord, ...normalized.opsThreads];
  const history = normalized.history.map(item => (
    item.id === focusedHistoryId
      ? {
          ...item,
          issueThread: {
            id: threadId,
            requestId,
            receiptHash,
            href: `#issue-thread-${encodeURIComponent(threadId)}`,
            status: "open",
            syncedAt: stamp,
          },
        }
      : item
  ));
  return {
    ...normalized,
    focusedHistoryId,
    updatedAt: stamp,
    opsThreads,
    history,
    annotationReadiness: {
      ...normalized.annotationReadiness,
      activeThreadRef: threadId,
    },
  };
}
